project_id = "lxfkdvzuthvkvkhqaaed"

[functions.send-confirmation-email]
verify_jwt = false

[functions.google-maps]
verify_jwt = false

[functions.send-offer-notification]
verify_jwt = false

[functions.send-offer-accepted]
verify_jwt = false

[functions.send-job-status-notification]
verify_jwt = false
